class Calculator:
    def square(self, number):
        return number ** 2

    def cube(self, number):
        return number ** 3

    def square_root(self, number):
        return number ** 0.5


calc = Calculator()
print(calc.square(5))         # Output: 25
print(calc.cube(5))           # Output: 125
print(round(calc.square_root(5), 2))  # Output: 5.0


#this solution was generated by ai !!

